<?php

declare(strict_types=1);

use Phinx\Migration\AbstractMigration;


final class AppConfigData extends AbstractMigration
{
    use MigrationTrait;

    public function up(): void
    {
        $table = $this->table("app_config");

        $data = [
            ['key' => 'address', 'value' => '123 Nowhere street'],
            ['key' => 'allow_duplicate_barcodes', 'value' => '0'],
            ['key' => 'barcode_content', 'value' => 'id'],
            ['key' => 'barcode_first_row', 'value' => 'category'],
            ['key' => 'barcode_font', 'value' => 'Arial'],
            ['key' => 'barcode_font_size', 'value' => '10'],
            ['key' => 'barcode_formats', 'value' => '[]'],
            ['key' => 'barcode_generate_if_empty', 'value' => '0'],
            ['key' => 'barcode_height', 'value' => '50'],
            ['key' => 'barcode_num_in_row', 'value' => '2'],
            ['key' => 'barcode_page_cellspacing', 'value' => '20'],
            ['key' => 'barcode_page_width', 'value' => '100'],
            ['key' => 'barcode_second_row', 'value' => 'item_code'],
            ['key' => 'barcode_third_row', 'value' => 'unit_price'],
            ['key' => 'barcode_type', 'value' => 'Code39'],
            ['key' => 'barcode_width', 'value' => '250'],
            ['key' => 'cash_decimals', 'value' => '2'],
            ['key' => 'cash_rounding_code', 'value' => '0'],
            ['key' => 'company', 'value' => 'Vikuraa'],
            ['key' => 'company_logo', 'value' => ''],
            ['key' => 'country_codes', 'value' => 'us'],
            ['key' => 'currency_code', 'value' => ''],
            ['key' => 'currency_decimals', 'value' => '2'],
            ['key' => 'currency_symbol', 'value' => '$'],
            ['key' => 'customer_reward_enable', 'value' => '0'],
            ['key' => 'dateformat', 'value' => 'm/d/Y'],
            ['key' => 'date_or_time_format', 'value' => ''],
            ['key' => 'default_receivings_discount', 'value' => '0'],
            ['key' => 'default_receivings_discount_type', 'value' => '0'],
            ['key' => 'default_register_mode', 'value' => 'sale'],
            ['key' => 'default_sales_discount', 'value' => '0'],
            ['key' => 'default_sales_discount_type', 'value' => '0'],
            ['key' => 'default_tax_1_name', 'value' => ''],
            ['key' => 'default_tax_1_rate', 'value' => ''],
            ['key' => 'default_tax_2_name', 'value' => ''],
            ['key' => 'default_tax_2_rate', 'value' => ''],
            ['key' => 'default_tax_category', 'value' => 'Standard'],
            ['key' => 'default_tax_code', 'value' => ''],
            ['key' => 'default_tax_jurisdiction', 'value' => ''],
            ['key' => 'default_tax_rate', 'value' => '8'],
            ['key' => 'derive_sale_quantity', 'value' => '0'],
            ['key' => 'dinner_table_enable', 'value' => '0'],
            ['key' => 'email', 'value' => 'changeme@example.com'],
            ['key' => 'email_receipt_check_behaviour', 'value' => 'last'],
            ['key' => 'enforce_privacy', 'value' => '0'],
            ['key' => 'fax', 'value' => ''],
            ['key' => 'financial_year', 'value' => '1'],
            ['key' => 'gcaptcha_enable', 'value' => '0'],
            ['key' => 'gcaptcha_secret_key', 'value' => ''],
            ['key' => 'gcaptcha_site_key', 'value' => ''],
            ['key' => 'giftcard_number', 'value' => 'series'],
            ['key' => 'image_allowed_types', 'value' => 'gif|jpg|png'],
            ['key' => 'image_max_height', 'value' => '480'],
            ['key' => 'image_max_size', 'value' => '128'],
            ['key' => 'image_max_width', 'value' => '640'],
            ['key' => 'include_hsn', 'value' => '0'],
            ['key' => 'invoice_default_comments', 'value' => 'This is a default comment'],
            ['key' => 'invoice_email_message', 'value' => 'Dear {CU}, In attachment the receipt for sale {ISEQ}'],
            ['key' => 'invoice_enable', 'value' => '1'],
            ['key' => 'invoice_type', 'value' => 'invoice'],
            ['key' => 'language', 'value' => 'english'],
            ['key' => 'language_code', 'value' => 'en-US'],
            ['key' => 'last_used_invoice_number', 'value' => '0'],
            ['key' => 'last_used_quote_number', 'value' => '0'],
            ['key' => 'last_used_work_order_number', 'value' => '0'],
            ['key' => 'lines_per_page', 'value' => '25'],
            ['key' => 'line_sequence', 'value' => '0'],
            ['key' => 'login_form', 'value' => 'floating_labels'],
            ['key' => 'mailpath', 'value' => '/usr/sbin/sendmail'],
            ['key' => 'msg_msg', 'value' => ''],
            ['key' => 'msg_pwd', 'value' => ''],
            ['key' => 'msg_src', 'value' => ''],
            ['key' => 'msg_uid', 'value' => ''],
            ['key' => 'multi_pack_enabled', 'value' => '0'],
            ['key' => 'notify_horizontal_position', 'value' => 'center'],
            ['key' => 'notify_vertical_position', 'value' => 'bottom'],
            ['key' => 'number_locale', 'value' => 'en_US'],
            ['key' => 'payment_options_order', 'value' => 'cashdebitcredit'],
            ['key' => 'phone', 'value' => '555-555-5555'],
            ['key' => 'print_bottom_margin', 'value' => '0'],
            ['key' => 'print_delay_autoreturn', 'value' => '0'],
            ['key' => 'print_footer', 'value' => '0'],
            ['key' => 'print_header', 'value' => '0'],
            ['key' => 'print_left_margin', 'value' => '0'],
            ['key' => 'print_receipt_check_behaviour', 'value' => 'last'],
            ['key' => 'print_right_margin', 'value' => '0'],
            ['key' => 'print_silently', 'value' => '1'],
            ['key' => 'print_top_margin', 'value' => '0'],
            ['key' => 'protocol', 'value' => 'mail'],
            ['key' => 'quantity_decimals', 'value' => '0'],
            ['key' => 'quote_default_comments', 'value' => 'This is a default quote comment'],
            ['key' => 'receipt_font_size', 'value' => '12'],
            ['key' => 'receipt_show_company_name', 'value' => '1'],
            ['key' => 'receipt_show_description', 'value' => '1'],
            ['key' => 'receipt_show_serialnumber', 'value' => '1'],
            ['key' => 'receipt_show_taxes', 'value' => '0'],
            ['key' => 'receipt_show_tax_ind', 'value' => '0'],
            ['key' => 'receipt_show_total_discount', 'value' => '1'],
            ['key' => 'receipt_template', 'value' => 'receipt_default'],
            ['key' => 'receiving_calculate_average_price', 'value' => '0'],
            ['key' => 'recv_invoice_format', 'value' => '{CO}'],
            ['key' => 'return_policy', 'value' => 'Test'],
            ['key' => 'sales_invoice_format', 'value' => '{CO}'],
            ['key' => 'sales_quote_format', 'value' => 'Q%y{QSEQ:6}'],
            ['key' => 'smtp_crypto', 'value' => 'ssl'],
            ['key' => 'smtp_host', 'value' => ''],
            ['key' => 'smtp_pass', 'value' => ''],
            ['key' => 'smtp_port', 'value' => '465'],
            ['key' => 'smtp_timeout', 'value' => '5'],
            ['key' => 'smtp_user', 'value' => ''],
            ['key' => 'suggestions_first_column', 'value' => 'name'],
            ['key' => 'suggestions_second_column', 'value' => ''],
            ['key' => 'suggestions_third_column', 'value' => ''],
            ['key' => 'tax_decimals', 'value' => '2'],
            ['key' => 'tax_id', 'value' => ''],
            ['key' => 'tax_included', 'value' => '0'],
            ['key' => 'theme', 'value' => 'flatly'],
            ['key' => 'thousands_separator', 'value' => '1'],
            ['key' => 'timeformat', 'value' => 'H:i:s'],
            ['key' => 'timezone', 'value' => 'America/New_York'],
            ['key' => 'use_destination_based_tax', 'value' => '0'],
            ['key' => 'website', 'value' => ''],
            ['key' => 'work_order_enable', 'value' => '0'],
            ['key' => 'work_order_format', 'value' => 'W%y{WSEQ:6}'],
        ];

        $table->insert($data)->save();
    }

    public function down(): void
    {
        $this->execute("DELETE FROM app_config");
    }
}
